package ventanas;

import com.leguizamon.dissist.MisFunciones;
import com.leguizamon.dissist.OrdenProduccion;
import com.leguizamon.dissist.Ordenes;
import com.leguizamon.dissist.Turno;
import com.leguizamon.dissist.Turnos;
import java.util.ArrayList;
import java.util.Calendar;

public class VentanaReanudarOP extends javax.swing.JInternalFrame {

    private final OrdenProduccion ordenProduccion;
    private String fecha;
    private final int horaActual;
    private final Turno turno;

    /**
     * Creates new form VentanaReanudarOP
     *
     * @param ordenProduccion
     */
    public VentanaReanudarOP(OrdenProduccion ordenProduccion) {
        this.ordenProduccion = ordenProduccion;
        initComponents();
        MisFunciones.configVentana(this);

        Calendar cal = Calendar.getInstance();
        fecha = MisFunciones.getFechaActual();

        horaActual = cal.get(Calendar.HOUR_OF_DAY);

        turno = MisFunciones.getTurnoByHora(horaActual);
        txtTurno.setText(turno.getNombre());
        lblHorarios.setText(String.format("De "+ MisFunciones.completarHora(turno.getInicio()) + " a " + MisFunciones.completarHora(turno.getFin())));
        txtHoraInicio.setText(String.valueOf(horaActual));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReanudar = new javax.swing.JButton();
        lblHorarios = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();

        setTitle("REANUDAR ORDEN DE PRODUCCIÓN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Turno");

        btnReanudar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReanudar.setText("REANUDAR");
        btnReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReanudarActionPerformed(evt);
            }
        });

        lblHorarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHorarios.setText("Horarios");

        txtTurno.setEditable(false);
        txtTurno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Hora de Inicio");

        txtHoraInicio.setEditable(false);
        txtHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtHoraInicio)))
                    .addComponent(lblHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHorarios)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnReanudar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudarActionPerformed
        Ordenes o = new Ordenes();
        o.reanudarOP(ordenProduccion, fecha, turno, horaActual);
        dispose();
        VentanaGestionarOP v = new VentanaGestionarOP();
        v.seleccionarOrden(ordenProduccion);
    }//GEN-LAST:event_btnReanudarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReanudar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
