package ventanas;

import com.leguizamon.dissist.Hora;
import com.leguizamon.dissist.Horas;
import com.leguizamon.dissist.MisFunciones;
import com.leguizamon.dissist.OrdenProduccion;
import com.leguizamon.dissist.Turno;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class VentanaCrearObjetivo extends javax.swing.JInternalFrame {

    Horas horas = new Horas();
    ArrayList<Hora> arrayHoras;
    private final OrdenProduccion ordenProduccion;
    private final Turno turno;

    /**
     * Creates new form VentanaNuevoObjetivo
     *
     * @param ordenProduccion
     */
    public VentanaCrearObjetivo(OrdenProduccion ordenProduccion) {
        this.ordenProduccion = ordenProduccion;
        turno = ordenProduccion.getTurno();
        arrayHoras = horas.getArrayHoras();

        initComponents();

        MisFunciones.configVentana(this);

        txtNumeroOrden.setText(String.valueOf(ordenProduccion.getNumeroOrden()));
        txtTurno.setText(turno.getNombre());

        if (turno.getInicio() == 22) {
            cbHorarios.addItem("22");
            cbHorarios.addItem("23");
            cbHorarios.addItem("0");
            cbHorarios.addItem("1");
            cbHorarios.addItem("2");
            cbHorarios.addItem("3");
            cbHorarios.addItem("4");
            cbHorarios.addItem("5");
        } else {
            for (int inicio = turno.getInicio(); inicio < turno.getFin(); inicio++) {
                cbHorarios.addItem(String.valueOf(inicio));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        txtObjetivo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroOrden = new javax.swing.JTextField();
        cbHorarios = new javax.swing.JComboBox<>();

        setTitle("AGREGAR OBJETIVO");
        setFrameIcon(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Turno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hora");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Objetivo");

        txtTurno.setEditable(false);
        txtTurno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTurno.setFocusable(false);

        txtObjetivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nº Orden");

        txtNumeroOrden.setEditable(false);
        txtNumeroOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroOrden.setFocusable(false);

        cbHorarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTurno)
                            .addComponent(txtObjetivo, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtNumeroOrden)
                            .addComponent(cbHorarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(36, 36, 36))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
        VentanaGestionarOP v = new VentanaGestionarOP();
        v.seleccionarOrden(ordenProduccion);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int hora = Integer.parseInt(cbHorarios.getSelectedItem().toString());
        if (txtObjetivo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el objetivo");
        } else {
            Boolean existeHora = false;
            for (Hora h : arrayHoras) {
                if (h.getNumeroOrden() == ordenProduccion.getNumeroOrden()) {
                    if (h.getHora() == hora && h.getFecha().equals(ordenProduccion.getFecha())) {
                        existeHora = true;
                    }
                }
            }
            if (existeHora) {
                JOptionPane.showMessageDialog(null, "Ya existen objetivos para la hora seleccionada");
            } else {
                int id = MisFunciones.getProximoIdHoras();
                int numeroOrden = ordenProduccion.getNumeroOrden();
                String fecha = ordenProduccion.getFecha();

                int objetivo = Integer.parseInt(txtObjetivo.getText());

                Horas horas = new Horas();
                Hora nuevaHora = new Hora(id, numeroOrden, fecha, hora, objetivo);
                horas.agregarHora(nuevaHora);

                dispose();
                VentanaGestionarOP v = new VentanaGestionarOP();
                v.seleccionarOrden(ordenProduccion);
            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbHorarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNumeroOrden;
    private javax.swing.JTextField txtObjetivo;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
