package ventanas;

import com.leguizamon.dissist.Mdi;
import com.leguizamon.dissist.MisFunciones;
import com.leguizamon.dissist.Usuario;
import com.leguizamon.dissist.Usuarios;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

public class VentanaGestionarUsuarios extends javax.swing.JInternalFrame {
    
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<Usuario> arrayUsuarios = new ArrayList<>();

    /**
     * Creates new form VentanaGestionarUsuarios
     */
    public VentanaGestionarUsuarios() {
        initComponents();
        MisFunciones.configVentana(this);
        arrayUsuarios = Mdi.getArrayUsuarios();
        setModelo(arrayUsuarios);
        
        tablaUsuarios.getSelectionModel().addListSelectionListener((ListSelectionEvent evt) -> {
            btnAgregar.setEnabled(true);
            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(true);
        });
        
    }
    
    public void setModelo(ArrayList<Usuario> arrayUsuarios) {
        String[] cabecera = {"DNI", "APELLIDO", "NOMBRE", "EMAIL", "TIPO DE USUARIO"};
        model.setColumnIdentifiers(cabecera);
        Object datos[] = new Object[model.getColumnCount()];
        for (Usuario u : arrayUsuarios) {
            datos[0] = u.getDni();
            datos[1] = u.getApellido();
            datos[2] = u.getNombre();
            datos[3] = u.getEmail();
            datos[4] = u.getTipoUsuario();
            model.addRow(datos);
        }
        tablaUsuarios.setModel(model);
    }
    
    public void seleccionarUsuario(Usuario usuario) {
        for (int i = 0; i < tablaUsuarios.getRowCount(); i++) {
            if (tablaUsuarios.getValueAt(i, 0).toString().equals(usuario.getDni())) {
                tablaUsuarios.changeSelection(i, 0, false, false);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        dispose();
        VentanaCrearUsuario v = new VentanaCrearUsuario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
        VentanaAdministrador v = new VentanaAdministrador();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tablaUsuarios.getSelectedRow();
        String dni = model.getValueAt(fila, 0).toString();
        dispose();
        VentanaEditarUsuario v = new VentanaEditarUsuario(dni);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaUsuarios.getSelectedRow();
        String dni = model.getValueAt(fila, 0).toString();
        Usuarios usuarios = new Usuarios();
        usuarios.eliminarUsuario(dni);
        arrayUsuarios = Mdi.getArrayUsuarios();
        model.setRowCount(0);
        setModelo(arrayUsuarios);
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
